linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: sagikazarmark.dev/mga

linters:
    enable-all: true
    disable:
        - maligned
        - funlen
        - dupl
        - wsl
        - gomnd

        # TODO: fixme
        - godox
        - gocognit

service:
    golangci-lint-version: 1.20.x
