name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Lint
        uses: actions-contrib/golangci-lint@v1
        with:
          golangci_lint_version: v1.23

      - name: Generate code
        run: make generate

      - name: Test
        run: make test
